This is makeindex, version 2.16 [MiKTeX 25.12].
Scanning style file ./UNAMdissertemplate.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file UNAMdissertemplate.acn....done (20 entries accepted, 0 rejected).
Sorting entries....done (87 comparisons).
Generating output file UNAMdissertemplate.acr....done (21 lines written, 0 warnings).
Output written in UNAMdissertemplate.acr.
Transcript written in UNAMdissertemplate.alg.
